"""Init

Revision ID: 0678c78e420e
Revises: 
Create Date: 2024-01-13 11:23:57.915214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0678c78e420e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts", sa.Column("firstname", sa.String(length=25), nullable=True)
    )
    op.add_column(
        "contacts", sa.Column("lastname", sa.String(length=25), nullable=True)
    )
    op.drop_column("contacts", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("contacts", "lastname")
    op.drop_column("contacts", "firstname")
    # ### end Alembic commands ###
